name: Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -  name: hellow world
         run:  echo  "Hello World"
         shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye world
        run:  echo "Goodbye World"
        shell: bash
    
      
      
    
